# -*- coding: utf-8 -*-
"""sales_app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1y2svHNDjr2mxiF1iPGZz4q-lCiibmzan
"""

import streamlit as st
import pandas as pd

# Title and subheader
st.title("Sales Summary Dashboard")
st.subheader("Interactive sales summary with category filter")

# Hardcoded dataset (5 rows, 3 columns minimum)
data = {
    "Product": ["Laptop", "Phone", "Tablet", "Monitor", "Keyboard"],
    "Category": ["Electronics", "Electronics", "Electronics", "Accessories", "Accessories"],
    "Sales": [50000, 30000, 20000, 15000, 5000]
}

df = pd.DataFrame(data)

# Sidebar filter
st.sidebar.title("Filter Options")

category = st.sidebar.selectbox(
    "Select Category",
    df["Category"].unique()
)

# Filter data
filtered_df = df[df["Category"] == category]

# Main content
st.write(f"Showing sales data for: {category}")

# Display filtered table
st.dataframe(filtered_df)

# Display line chart
st.line_chart(filtered_df["Sales"])